### ISSUE TITLE
install in 2.79 stable version or 2.79.4, butt shows errors 

### ISSUE THREAD

**Issue by CJYen** [jasperges/pose-thumbnails#56]
Traceback (most recent call last):
  File "D:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\joe\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\pose_thumbnails\__init__.py", line 43, in <module>
    from . import core, creation
  File "C:\Users\joe\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\pose_thumbnails\core.py", line 509
    pose_index: bpy.props.IntProperty(
              ^
SyntaxError: invalid syntax

**Comment by jasperges** [comment]
I think you got the add-on from @sybrenstuvel's github. As far as I can see, he made some updates to make it compatible with Blender 2.80. The syntax error you see is for code that doesn't work on Python 3.5 (the Python version used by Blender 2.79b). So you have 2 options: download the official version from the [release page of this Github repository](https://github.com/jasperges/pose-thumbnails/releases) or use a Blender version from the [buildbot](https://builder.blender.org/download/).
